
# This is a basic workflow to help you get started with Actions

name: Ragnarok Madness CI and CD

# Controls when the workflow will run
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]
  workflow_dispatch:


jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest] # macOS was chosen because of how the runner interprets the file paths. File paths are having problems when used in other runners. 
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Downloading the Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          
      - name: Check resource
        run : | 
          cd res
          ls
          cd sounds 
          echo sound files are:
          ls
          cd ..
          cd ..
        
        # Runs a set of commands using the runners shell
      - name: Compiling, Testing and Packaging with 1 maven step.
        run: mvn --batch-mode --update-snapshots verify

      - name: check build exists
        run : |
          cd bin/
          ls -a
          
          
  report-generation:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest] # macOS was chosen because of how the runner interprets the file paths. File paths are having problems when used in other runners. 
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Downloading the Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
        
      - name: Generating report of the Static Analyzer
        run: mvn site
        
      - name : Checking if Report is created
        run : |
          cd bin/site/
          ls -a
        
      - name : Creatig artifact for PMD reports
        uses: actions/upload-artifact@v2
        with:
            name: report-artifact
            path: bin/site

  javadoc-generation:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest] # macOS was chosen because of how the runner interprets the file paths. File paths are having problems when used in other runners. 
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Downloading the Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
        
      - name : Generting javadoc
        run : find src_rm_java/ragmad -type f -name "*.java" | xargs javadoc -d docs
        
      - name : Checking if javadoc created
        run : ls
        
      - name : Creatig artifact for javadocs
        uses: actions/upload-artifact@v2
        with:
            name: javadoc-artifact
            path: docs
