# This is a basic workflow to help you get started with Actions

name: Ragnarok Madness CI and CD

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Downloading the Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      # Runs a set of commands using the runners shell
      - name: Downloading depencies and testing the project
        run: mvn test --file pom.xml -Djava.awt.headless=true # though this is the default file.

      # Runs a set of commands using the runners shell
      - name: Compiling the project
        run: mvn compile --file pom.xml -Djava.awt.headless=true # though this is the default file.


        # Runs a set of commands using the runners shell
      - name: Packaging into .jar file
        run: mvn package --file pom.xml -Djava.awt.headless=true # though this is the default file.

      - name: check build exists
        run : |
          cd bin/
          ls -a
        